version: '3.8'

services:
  # ---------------------------------------------------------
  # Banco de Dados Principal (Relacional)
  # ---------------------------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: agrobasis_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: agro
      POSTGRES_DB: agrobasis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ---------------------------------------------------------
  # Cache e Mensageria em Memória
  # ---------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: agrobasis_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
