spring:
  application:
    name: agrobasis-core

  datasource:
    url: jdbc:postgresql://localhost:5432/agrobasis_db
    username: admin
    password: agro
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:Zm9yLWRldmVsb3BtZW50LW9ubHktand0LXNlY3JldC1tdXN0LWJlLWxvbmdlbm91Z2g=}
  expiration: ${JWT_EXPIRATION:43200000}
