spring:
  application:
    name: agrobasis-core

  datasource:
    url: jdbc:postgresql://localhost:5432/agrobasis_db
    username: admin
    password: agro
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  flyway:
    enabled: true